INF272 del3/INF272 del3/Controllers/AdminBusController.cs
using INF272_del3.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Data.Entity;
using System.Net;


namespace INF272_del3.Controllers
{
    public class AdminBusController : Controller
    {
        private LinkDatabaseTDOEntities4 db = new LinkDatabaseTDOEntities4();
        // GET: AdminBus
        public ActionResult Index()
        {
            var business_Category = db.Business_Category.Include(b => b.Image).Include(z=>z.Freelancers);
            
            return View(business_Category.ToList());
           
        }

        // GET: Business_Category/Details/5
      

        // GET: Business_Category/Create
        public ActionResult Create()
        {
            ViewBag.ImageID = new SelectList(db.Images, "ImageID", "ImgSource");
            return View();
        }

        // POST: Business_Category/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BusinessCategoryID,Business_Categoty,ImageID")] Business_Category business_Category, HttpPostedFileBase file)
        {
            string path = Path.Combine(Server.MapPath("~/Images"), Path.GetFileName(file.FileName));
            file.SaveAs(path);

            Image img = new Image();
            img.ImgSource = "~/Images/" + file.FileName;
            db.Images.Add(img);
            db.SaveChanges();
            int imageID = img.ImageID;

            if (ModelState.IsValid)
            {
                business_Category.ImageID = imageID;
                db.Business_Category.Add(business_Category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ImageID = new SelectList(db.Images, "ImageID", "ImgSource", business_Category.ImageID);
            return View(business_Category);
        }

        // GET: Business_Category/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Business_Category business_Category = db.Business_Category.Find(id);
            if (business_Category == null)
            {
                return HttpNotFound();
            }
            ViewBag.ImageID = new SelectList(db.Images, "ImageID", "ImgSource", business_Category.ImageID);
            return View(business_Category);
        }

        // POST: Business_Category/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( Business_Category business_Category)
        {

            int bid = business_Category.BusinessCategoryID;
            var category = db.Business_Category.Where(x => x.BusinessCategoryID == bid).FirstOrDefault();
            if (ModelState.IsValid)
            {
                category.Business_Categoty = business_Category.Business_Categoty;
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
            }
            
            return RedirectToAction("Index"); ;
        }

        // GET: Business_Category/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Business_Category business_Category = db.Business_Category.Find(id);
            if (business_Category == null)
            {
                return HttpNotFound();
            }
            return View(business_Category);
        }

        // POST: Business_Category/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Business_Category business_Category = db.Business_Category.Find(id);
            db.Business_Category.Remove(business_Category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}
    

INF272 del3/INF272 del3/Views/AdminBus/Create.cshtml
@model INF272_del3.Models.Business_Category

    <head>
        <style>
            [hidden] {
                display: none !important;
            }
        </style>
        <script>
            function readURL(input) {
                if (input.files && input.files[0]) {
                    var reader = new FileReader();

                    reader.onload = function (e) {
                        $('#ImageId')
                            .attr('src', e.target.result);
                    };

                    reader.readAsDataURL(input.files[0]);
                }
            }
        </script>
    </head>

<div class="navbar bg-primary navbar-expand-lg navbar-fixed-top" style="margin-bottom:5rem">
    <div style="padding:4px">
        <a class="navbar-brand" href="#">
            <img src="~/Pictures/Logo2.jpg" alt="logo" style="width:75px;border-radius: 15px;">
        </a>
    </div>
    <div style="margin-top:0.2rem; margin-left:80%">
        <span class="navbar-text" style="padding-right:1rem">
            Admin
        </span>
        <span> <i class="glyphicon glyphicon-user" style="font-size:35px;cursor:pointer "></i></span>
        <span style="padding-left:2rem;font-size:25px;cursor:pointer" class="glyphicon glyphicon-log-out" data-toggle="modal" data-target="#logout"></span>
    </div>
</div>

<div class="container" style="padding-top:4rem">


    <div class="modal fade" id="logout" tabindex="-1" role="dialog" aria-labelledby="logoutCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteLongTitle">Logout</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Would you like to logout?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-secondary" onclick="location.href='@Url.Action("Index", "Login")'">Confirm</button>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
       
        

        @using (Html.BeginForm("Create", "AdminBus", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

        <div class="container" style="padding-bottom:1rem">
            <h2>Add Category</h2>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                <label>Category name:</label>

                @Html.EditorFor(model => model.Business_Categoty, new { htmlAttributes = new { @class = "form-control", @style = "width:200px" } })
                @Html.ValidationMessageFor(model => model.Business_Categoty, "", new { @class = "text-danger" })

            </div>

           <br />

            <div class="control-group">

                <div class="controls">
                    <div class="form-group">
                        
                        <label class="btn btn-primary">
                            <i class="glyphicon glyphicon-folder-open"></i><input type="file" name="file" onchange="readURL(this)" hidden>
                        </label><label style="margin-left:1rem">Upload photo</label>
                    </div>

                    <img id="ImageId" style="height:150px; width:170px; object-fit:fill; border-radius:15px; border:solid; color:lightgray" />
                </div>
            </div>
            <br />
            <div class="form-group" style="margin-left:1000px;margin-top:2rem">
                <div >
                    <input type="submit" value="Create" class="btn btn-default" style="width:100px" />
                </div>
            </div>
        </div>
        }
        <div style="margin-left:1018px">
            <button class="btn btn-default" style="width:100px" onclick="location.href='@Url.Action("Index", "AdminBus")'" >Back </button>
        </div>
    </div>
</div>

INF272 del3/INF272 del3/Views/AdminBus/Delete.cshtml
@model INF272_del3.Models.Business_Category

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayName("Business category:")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Business_Categoty)
        </dd>

        <dt>
            @Html.DisplayName("Image:")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image.ImgSource)

        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

INF272 del3/INF272 del3/Views/AdminBus/Edit.cshtml
@model INF272_del3.Models.Business_Category

@{
    ViewBag.Title = "Edit";
}

<div class="navbar bg-primary navbar-expand-lg navbar-fixed-top" style="margin-bottom:5rem">
    <div style="padding:4px">
        <a class="navbar-brand" href="#">
            <img src="~/Pictures/Logo2.jpg" alt="logo" style="width:75px;border-radius: 15px;">
        </a>
    </div>
    <div style="margin-top:0.2rem; margin-left:80%">
        <span class="navbar-text" style="padding-right:1rem">
            Admin
        </span>
        <span> <i class="glyphicon glyphicon-user" style="font-size:35px;cursor:pointer "></i></span>
        <span style="padding-left:2rem;font-size:25px;cursor:pointer" class="glyphicon glyphicon-log-out" data-toggle="modal" data-target="#logout"></span>
    </div>
</div>

<div class="row" style="padding-top:4rem">
    <div class="col-md-5">
        <h4 > Edit Business Catergory </h4>
    </div>
    <div class="container" style="padding-top:4rem">
        <div class="modal fade" id="logout" tabindex="-1" role="dialog" aria-labelledby="logoutCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="deleteLongTitle">Logout</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        Would you like to logout?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <button type="button" class="btn btn-secondary" onclick="location.href='@Url.Action("Login", "Login")'">Confirm</button>
                    </div>
                </div>
            </div>
        </div>
        
        @using (Html.BeginForm("Edit", "AdminBus", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                <hr />

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.BusinessCategoryID)

                <div class="form-group">
                   
                    <div class="col-md-10">
                        @Html.DisplayName("Business category")
                        @Html.EditorFor(model => model.Business_Categoty, new { htmlAttributes = new { @class = "form-control", @style ="width:200px" } })
                        @Html.ValidationMessageFor(model => model.Business_Categoty, "", new { @class = "text-danger" })
                    </div>
                </div>
                <br />

                <div class="form-group" style="margin-right:820px">
                   
                    <div class="col-md-10">
                        @Html.DisplayName("Image")
                        <input type="file" name="file" />
                    </div>
                </div>

                <div class="form-group" style="margin-left:960px">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" style="width:106px" />
                    </div>
                </div>
            </div>
        }
    <div style="margin-left:1010px">
        <button class="btn btn-default" style="width:100px" onclick="location.href='@Url.Action("Index", "AdminBus")'">Back </button>
    </div>
    </div>
    </div>

INF272 del3/INF272 del3/Views/AdminBus/Index.cshtml
@model IEnumerable<INF272_del3.Models.Business_Category>

@{
    ViewBag.Title = "Index";
}

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.22/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/0.4.1/html2canvas.min.js"></script>
<script type="text/javascript">
    function Export() {
        html2canvas(document.getElementById('table'), {
            onrendered: function (canvas) {
                var data = canvas.toDataURL();
                var docDefinition = {
                    content: [{
                        image: data,
                        width: 500
                    }]
                };
                pdfMake.createPdf(docDefinition).download("Table.pdf");
            }
        });
    }
</script>


<div class="navbar bg-primary navbar-expand-lg navbar-fixed-top" style="margin-bottom:5rem">
    <div style="padding:4px">
        <a class="navbar-brand" href="#">
            <img src="~/Pictures/Logo2.jpg" alt="logo" style="width:75px;border-radius: 15px;">
        </a>
    </div>
    <div style="margin-top:0.2rem; margin-left:80%">
        <span class="navbar-text" style="padding-right:1rem">
            Admin
        </span>
        <span> <i class="glyphicon glyphicon-user" style="font-size:35px;cursor:pointer "></i></span>
        <span style="padding-left:2rem;font-size:25px;cursor:pointer" class="glyphicon glyphicon-log-out" data-toggle="modal" data-target="#logout"></span>
    </div>
</div>


<div class="container" style="padding-top:4rem;padding-bottom:10rem">
    <div class="modal fade" id="logout" tabindex="-1" role="dialog" aria-labelledby="logoutCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteLongTitle">Logout</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Would you like to logout?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-secondary" onclick="location.href='@Url.Action("Index", "Login")'">Confirm</button>
                </div>
            </div>
        </div>
    </div>

    <div class="row" style="padding-top:1rem">
        <div class="col-md-5" style="padding-bottom:1.5rem">
            <h2 style=""> Current Business Catergories </h2>
        </div>


        <div class="container" >
            <table id="table" class="table  table-hover table-responsive"
                   style="margin-left: auto;padding-bottom:1rem">
                <tr>
                    <th>
                        Business catgories
                    </th>
                    <th>
                       # of freelancrs
                    </th>
                    <th>
                        Background
                    </th>
                    <th></th>

                </tr>

                @foreach (var item in Model)
                {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Business_Categoty)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Freelancers.Count)
                </td>
                <td>
                    <img src="@Url.Content(item.Image.ImgSource) " style="width:75px;height:60px" />
                </td>

                <td>

                    <button class="btn btn-success" onclick="location.href='@Url.Action("Edit", "AdminBus", new { id = item.BusinessCategoryID })'"><i class="glyphicon glyphicon-pencil"> </i>  </button>
                    <button class="btn btn-danger" onclick="location.href='@Url.Action("Delete", "AdminBus", new { id = item.BusinessCategoryID })'"><i class="glyphicon glyphicon-trash"> </i>  </button>

                </td>

            </tr>
                }
            </table>

        </div>
        <div >
            <div style="float:right;">
                <button class="btn btn-primary btn-sm " style="width:86px" onclick='window.location.href = "@Url.Action("Create")"'>Add New</button>
                <div style="padding-top:1rem">
                    <input type="button" id="btnExport" onclick="Export()" class="btn btn-primary btn-sm" value="Print Report">

                </div>
                <div style="padding-top:1rem">
                    <button class="btn btn-primary btn-sm " style="width:87px" onclick="location.href='@Url.Action("Index", "Users")'">Go Back</button>
                </div>


            </div>
        </div>
    </div>
</div>