INF272 del3/INF272 del3/Models/Employer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF272_del3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employer()
        {
            this.EMP_Freelancer = new HashSet<EMP_Freelancer>();
        }
    
        public int EmployerID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string BusinessName { get; set; }
        public Nullable<int> SubhurbID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMP_Freelancer> EMP_Freelancer { get; set; }
        public virtual Subhurb Subhurb { get; set; }
        public virtual User User { get; set; }
    }
}

INF272 del3/INF272 del3/Controllers/EmployerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using INF272_del3.Models;

namespace INF272_del3.Controllers
{
    public class EmployerController : Controller
    {
        private LinkDatabaseTDOEntities4 db = new LinkDatabaseTDOEntities4();

        // GET: Employer
        public ActionResult Index( int id)
        {   Employer emp = db.Employers.Where(zz => zz.UserID == id).FirstOrDefault();
            ViewBag.emp = emp;
            User user = db.Users.Where(zz => zz.UserID == id).Include(zz => zz.Image).FirstOrDefault();
            ViewBag.user = user;
            TempData["eID"] = emp.EmployerID;
            TempData["uID"] = id;
            var businesscat = db.Business_Category.Include(b => b.Freelancers);
            return View(businesscat.ToList());
        }


        public ActionResult PotentialFreelancer(int id, int? h, int? zzz)
        {
            db.Configuration.ProxyCreationEnabled = false;
            List<Freelancer> free = db.Freelancers.Include(zz => zz.Subhurb).Include(zz => zz.Subhurb.City).Include(zz => zz.Subhurb.City.Province).Include(zz=>zz.User.Image).Where(zz => zz.BusinessCategoryID == id).ToList();
            var title = db.Business_Category.Where(zz => zz.BusinessCategoryID == id).Select(zz => zz.Business_Categoty).FirstOrDefault();
            var em = db.Employers.Include(zz => zz.User).Where(zz => zz.EmployerID == h).Select(zz => zz.UserID).FirstOrDefault();
            
          if(zzz == null)
            {
                ViewBag.zzz = em;
            }
            else
            {
                ViewBag.zzz = zzz;
            }
            

           
          
            ViewBag.title = title;
            TempData["zID"] = h;
            
             
            return View(free);
        }

        public ActionResult freeProfile(int? id)
        {
            Freelancer freelancer = db.Freelancers.Where(zz => zz.UserID == id).FirstOrDefault();
            ViewBag.fl = freelancer;
            ViewBag.city = freelancer.Subhurb.City.CityName;
            User user = db.Users.Where(zz => zz.UserID == id).Include(zz => zz.Image).FirstOrDefault();
            ViewBag.user = user;


            if (TempData["eID"] != null)
            {
                ViewBag.eID = (int)TempData["eID"];
            }
            else
            {
                ViewBag.eID = (int)TempData["zID"];
            }
            
         
            List<PortfolioImage> pf = db.PortfolioImages.Where(zz => zz.FreelancerID == freelancer.FreelancerID).Include(zz => zz.Image).Include(zz => zz.Freelancer).ToList();
            return View(pf);


        }


        public ActionResult PastBookings(int id)
        {
            List<EMP_Freelancer> book = db.EMP_Freelancer.Where(zz => zz.EmployerID == id).Include(zz => zz.Freelancer).Include(zz=>zz.Freelancer.Subhurb).ToList();
            var emp = book.Select(zz => zz.Employer.User.UserID).FirstOrDefault();
            ViewBag.user = emp;
            return View(book);
        }




    }
}

INF272 del3/INF272 del3/Views/Employers/Index.cshtml
@model WebApplication1.ViewModels.typeEmployer
@{
    ViewBag.Title = "Index";
}

<style>
    .zoom:hover {
        -ms-transform: scale(1.5);
        -webkit-transform: scale(1.5);
        transform: scale(1.5);
    }
</style>


<!--Modal to logout-->

<div class="container">
    <div>
        <span style="margin-left:96%; margin-top:2rem; font-size:20px" class="glyphicon glyphicon-lock" data-toggle="modal" data-target="#logout"></span>

        <div class="modal fade" id="logout" tabindex="-1" role="dialog" aria-labelledby="logoutCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h3 class="modal-title" id="deleteLongTitle">Do you want to log out?</h3>
                    </div>
                    <div class="modal-body">
                        You will loose all unsaved work if you log out. Press 'Cancel' to return to page or 'Confirm' to continue.
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <button type="button" class="btn btn-secondary" onclick="location.href='@Url.Action("Login", "Login")'">Confirm</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!--LOGO-->
    <div class="row" style="padding-bottom:50px">

        <div class="col-md-7">
            <div>
                <img style="width:50%; height:50%;" src="~/Pictures/Logo2.jpg" />
            </div>
        </div>
        <!--ICONS-->
        <div class="col-md-5">
            <i class="glyphicon glyphicon-user" style="font-size:100px; margin-bottom:1rem;"></i>
            <div style="float:left;margin-top:4rem;margin-left:20rem; margin-right:2rem;">
                <h4> Welcome</h4>
                <h5>@Model.Name</h5>
            </div>
        </div>

    </div>

    <div class="text-center" style=" color:purple">
        <h3>Select a category of work you are looking for:</h3><br /><br />
    </div>


    <div class="row" style="padding-top:2rem">
        <div class="col-md-4">
            <!--Plumber-->
            <div class="text-center">
                <button class="btn btn-lg zoom" onclick="location.href='@Url.Action("Index", "Freelancerts", new { })'"
                        style="width:300px;height:180px;background-image: url(/Pictures/plumb.jpg); background-repeat:no-repeat;
                                background-size:50%; background-size:cover;color:darkgray;font-size:20px;transition: transform 0.8s; border-radius:14px ">
                    Plumber
                </button>
            </div>
        </div>
        <!--Landscaping-->
        <div class="col-md-4">
            <div class="text-center">
                <button class="btn btn-lg zoom" onclick="location.href='@Url.Action("Index", "Freelancerts", new { /* id=item.PrimaryKey */ })'"
                        @*a id="btnViewUser" href="@Url.Action("ViewUser", new { ID = account.ID })" value="View" class="viewButton*@
                        style="width:300px;height:180px ;background-image: url(/Pictures/land.jpg); background-repeat:no-repeat;
                                            background-size:50%; background-size:cover;color:black;font-size:20px;transition: transform 0.8s; border-radius:14px">
                    Landscaping
                </button>
            </div>

        </div>

        <!--Photography-->
        <div class="col-md-4">
            <div class="text-center">
                <button class="btn btn-lg zoom" onclick="location.href='@Url.Action("Index", "Freelancerts")'"
                        style="width:300px;height:180px;background-image: url(/Pictures/photo.jpg); background-repeat:no-repeat;
                                  background-size:50%; background-size:cover;color:black;font-size:20px;transition: transform 0.8s; border-radius:14px ">
                    Photographer
                </button>
            </div>

        </div>
    </div>

    <!--Electrician-->
    <div class="row" style="padding-top:4rem">
        <div class="col-md-4">
            <div class="text-center">
                <button class="btn btn-lg zoom" onclick="location.href='@Url.Action("Index", "Freelancerts")'"
                        style="width:300px;height:180px;background-image: url(/Pictures/elec.jpg); background-repeat:no-repeat;
                               background-size:50%; background-size:cover;color:black;font-size:20px;transition: transform 0.8s; border-radius:14px ">
                    Electrician
                </button>
            </div>
        </div>

        <!--Painting-->
        <div class="col-md-4">
            <div class="text-center">
                <button class="btn btn-lg zoom" onclick="location.href = '@Url.Action("Index", "Freelancerts")'
                       " style="width:300px;height:180px;background-image: url(/Pictures/images.jpg); background-repeat:no-repeat;
                        background-size:50%; background-size:cover;color:black;font-size:20px;transition: transform 0.8s; border-radius:14px">
                    Painting
                </button>
            </div>

        </div>

        <!--Graphic Designer-->
        <div class="col-lg-4">
            <div class="text-center">
                <button class="btn btn-lg zoom" onclick="location.href='@Url.Action("Index", "Freelancerts")'"
                        style="width: 300px; height: 180px; background-image: url(/Pictures/graphic.jpg); background-size: cover;
                            color: white; font-size: 20px; transition: transform 0.8s; border-radius: 12px">
                    Graphic Designer
                </button>
            </div>

        </div>
    </div>
    }

</div>
<button class="btn btn-warning" style="float:right; margin-top:20px; margin-right:10px; background-color:purple;" onclick="location.href='@Url.Action("PastBookings", "Employer")'">Previous Bookings</button>